#include <neograph/hook.h>

#include "canonical_json.h"

#include <algorithm>
#include <stdexcept>
#include <tuple>

namespace neograph { namespace {
constexpr unsigned kMaxDepth = 8;
constexpr unsigned kMaxNodes = 64;
constexpr std::size_t kMaxPointerBytes = 1024;
constexpr std::size_t kMaxMappedBytes = 64U * 1024U;

std::string canonicalize(const json& value, const char* field) {
    const auto bytes = detail::canonical_json_bytes(value);
    if (bytes.size() > kMaxMappedBytes) throw std::invalid_argument(std::string(field) + " exceeds size limit");
    return bytes;
}
json canonical_json(const json& value, const char* field) {
    return detail::parse_json_strict(canonicalize(value, field));
}
void validate_pointer(std::string_view pointer, const char* field) {
    if (pointer.size() > kMaxPointerBytes) throw std::invalid_argument(std::string(field) + " exceeds size limit");
    detail::validate_json_pointer(pointer);
}
std::string digest(std::string_view domain, const json& value) {
    return detail::sha256_identity("NeoGraph Runtime identity v1", domain, detail::canonical_json_bytes(value));
}
bool phase_valid(HookPhase phase) { return static_cast<unsigned>(phase) <= static_cast<unsigned>(HookPhase::RunCancelled); }
bool delivery_valid(HookDelivery value) { return static_cast<unsigned>(value) <= static_cast<unsigned>(HookDelivery::DurableObservational); }
bool failure_valid(HookFailureMode value) { return static_cast<unsigned>(value) <= static_cast<unsigned>(HookFailureMode::Continue); }
bool idem_valid(HookIdempotency value) { return static_cast<unsigned>(value) <= static_cast<unsigned>(HookIdempotency::NonIdempotent); }
bool effect_valid(ToolEffectClass value) { return value >= ToolEffectClass::ReadOnly && value <= ToolEffectClass::ExternalWrite; }
void validate_phase(HookPhase phase) { if (!phase_valid(phase)) throw std::invalid_argument("Unknown hook phase"); }
void validate_delivery(HookDelivery value) { if (!delivery_valid(value)) throw std::invalid_argument("Unknown hook delivery"); }
void validate_failure(HookFailureMode value) { if (!failure_valid(value)) throw std::invalid_argument("Unknown hook failure mode"); }
void validate_idempotency(HookIdempotency value) { if (!idem_valid(value)) throw std::invalid_argument("Unknown hook idempotency"); }
void validate_effect(ToolEffectClass value) { if (!effect_valid(value)) throw std::invalid_argument("Unknown hook effect"); }
std::string delivery_name(HookDelivery value) { validate_delivery(value); return value == HookDelivery::BlockingMandatory ? "blocking_mandatory" : "durable_observational"; }
std::string failure_name(HookFailureMode value) { validate_failure(value); return value == HookFailureMode::FailClosed ? "fail_closed" : "continue"; }
std::string idempotency_name(HookIdempotency value) { validate_idempotency(value); return value == HookIdempotency::Idempotent ? "idempotent" : "non_idempotent"; }
std::string effect_name(ToolEffectClass value) { validate_effect(value); switch (value) { case ToolEffectClass::ReadOnly: return "read_only"; case ToolEffectClass::ExternalRead: return "external_read"; case ToolEffectClass::WorkspaceWrite: return "workspace_write"; case ToolEffectClass::ExternalWrite: return "external_write"; default: break; } throw std::invalid_argument("Unknown hook effect"); }
HookDelivery delivery_from_name(std::string_view value) { if (value == "blocking_mandatory") return HookDelivery::BlockingMandatory; if (value == "durable_observational") return HookDelivery::DurableObservational; throw std::invalid_argument("Unknown hook delivery"); }
HookFailureMode failure_from_name(std::string_view value) { if (value == "fail_closed") return HookFailureMode::FailClosed; if (value == "continue") return HookFailureMode::Continue; throw std::invalid_argument("Unknown hook failure mode"); }
HookIdempotency idem_from_name(std::string_view value) { if (value == "idempotent") return HookIdempotency::Idempotent; if (value == "non_idempotent") return HookIdempotency::NonIdempotent; throw std::invalid_argument("Unknown hook idempotency"); }
ToolEffectClass effect_from_name(std::string_view value) { if (value == "read_only") return ToolEffectClass::ReadOnly; if (value == "external_read") return ToolEffectClass::ExternalRead; if (value == "workspace_write") return ToolEffectClass::WorkspaceWrite; if (value == "external_write") return ToolEffectClass::ExternalWrite; throw std::invalid_argument("Unknown hook effect"); }

void validate_predicate(HookPredicate& value, unsigned depth, unsigned& nodes) {
    if (depth > kMaxDepth || ++nodes > kMaxNodes || static_cast<unsigned>(value.kind) > static_cast<unsigned>(HookPredicateKind::Exists) || static_cast<unsigned>(value.field) > static_cast<unsigned>(RuntimeEventField::DataPointer)) throw std::invalid_argument("Invalid hook predicate");
    const bool field_pointer = value.field == RuntimeEventField::DataPointer;
    if (field_pointer) validate_pointer(value.pointer, "Hook predicate pointer");
    else if (!value.pointer.empty()) throw std::invalid_argument("Typed hook predicate field cannot have a pointer");
    switch (value.kind) {
    case HookPredicateKind::True:
        if (value.field != RuntimeEventField::Type || !value.pointer.empty() || !value.children.empty() || !value.value.is_null()) throw std::invalid_argument("True predicate has operands"); break;
    case HookPredicateKind::All:
    case HookPredicateKind::Any:
        if (value.field != RuntimeEventField::Type || !value.pointer.empty() || value.children.empty() || value.children.size() > kMaxNodes || !value.value.is_null()) throw std::invalid_argument("Invalid compound hook predicate");
        for (auto& child : value.children) validate_predicate(child, depth + 1, nodes);
        break;
    case HookPredicateKind::Not:
        if (value.field != RuntimeEventField::Type || !value.pointer.empty() || value.children.size() != 1 || !value.value.is_null()) throw std::invalid_argument("Invalid negated hook predicate");
        validate_predicate(value.children.front(), depth + 1, nodes);
        break;
    case HookPredicateKind::Equals:
        if (!value.children.empty()) throw std::invalid_argument("Equals predicate has children");
        value.value = canonical_json(value.value, "Hook predicate value");
        break;
    case HookPredicateKind::Exists:
        if (!value.children.empty() || !value.value.is_null()) throw std::invalid_argument("Exists predicate has operands");
        break;
    }
}
void validate_template(const json& value, unsigned depth, unsigned& nodes) {
    if (depth > kMaxDepth || ++nodes > kMaxNodes) throw std::invalid_argument("Hook template exceeds bounds");
    if (value.is_object()) {
        if (value.contains("$event")) {
            if (value.size() != 1 || !value["$event"].is_string()) throw std::invalid_argument("Invalid hook template reference");
            validate_pointer(value["$event"].get<std::string>(), "Hook template pointer");
            return;
        }
        for (const auto& [key, child] : value.items()) { detail::validate_utf8(key); validate_template(child, depth + 1, nodes); }
    } else if (value.is_array()) for (const auto& child : value) validate_template(child, depth + 1, nodes);
}
void validate_mapper(HookInputMapper& mapper) {
    if (static_cast<unsigned>(mapper.kind) > static_cast<unsigned>(HookInputMapperKind::HostMapper)) throw std::invalid_argument("Unknown hook input mapper");
    if (mapper.kind == HookInputMapperKind::JsonPointer) { validate_pointer(mapper.json_pointer, "Hook input pointer"); if (!mapper.value_template.is_null() || !mapper.host_mapper_id.empty()) throw std::invalid_argument("JSON pointer mapper has extra fields"); }
    else if (mapper.kind == HookInputMapperKind::Template) { if (!mapper.json_pointer.empty() || !mapper.host_mapper_id.empty()) throw std::invalid_argument("Template mapper has extra fields"); unsigned nodes = 0; validate_template(mapper.value_template, 0, nodes); mapper.value_template = canonical_json(mapper.value_template, "Hook input template"); }
    else { if (!mapper.json_pointer.empty() || !mapper.value_template.is_null()) throw std::invalid_argument("Host mapper has extra fields"); detail::validate_token(mapper.host_mapper_id, "Hook host mapper id"); }
}
json event_body(const RuntimeEventData& d) { return {{"schema_version", RuntimeEvent::SCHEMA_VERSION}, {"sequence", d.sequence}, {"phase", std::string(to_string(d.phase))}, {"type", d.type}, {"owner_scope", d.owner_scope}, {"run_id", d.run_id}, {"data", d.data}}; }
json predicate_json(const HookPredicate& value) { json result = {{"kind", static_cast<unsigned>(value.kind)}, {"field", static_cast<unsigned>(value.field)}, {"pointer", value.pointer}, {"value", value.value}, {"children", json::array()}}; for (const auto& child : value.children) result["children"].push_back(predicate_json(child)); return result; }
HookPredicate predicate_from_json(const json& value) { if (!value.is_object()) throw std::invalid_argument("Invalid hook predicate"); detail::reject_unknown_fields(value, "Hook predicate", {"kind", "field", "pointer", "value", "children"}); HookPredicate result{static_cast<HookPredicateKind>(value.at("kind").get<unsigned>()), static_cast<RuntimeEventField>(value.at("field").get<unsigned>()), value.at("pointer").get<std::string>(), value.at("value"), {}}; if (!value.at("children").is_array()) throw std::invalid_argument("Hook predicate children must be an array"); for (const auto& child : value.at("children")) result.children.push_back(predicate_from_json(child)); return result; }
json capabilities_json(const std::set<std::string>& values) { json result = json::array(); for (const auto& value : values) result.push_back(value); return result; }
std::set<std::string> capabilities_from_json(const json& value) { if (!value.is_array()) throw std::invalid_argument("Hook capabilities must be an array"); std::set<std::string> result; for (const auto& capability : value) { const auto inserted = result.insert(capability.get<std::string>()); if (!inserted.second) throw std::invalid_argument("Duplicate hook capability"); } return result; }
json definition_body(const HookDefinitionData& d) { return {{"schema_version", HookDefinition::SCHEMA_VERSION}, {"priority", d.priority}, {"phase", std::string(to_string(d.phase))}, {"delivery", delivery_name(d.delivery)}, {"failure_mode", failure_name(d.failure_mode)}, {"idempotency", idempotency_name(d.idempotency)}, {"effect", effect_name(d.effect)}, {"target_id", d.target_id}, {"required_capabilities", capabilities_json(d.required_capabilities)}, {"predicate", predicate_json(d.predicate)}, {"input_mapper", {{"kind", static_cast<unsigned>(d.input_mapper.kind)}, {"json_pointer", d.input_mapper.json_pointer}, {"value_template", d.input_mapper.value_template}, {"host_mapper_id", d.input_mapper.host_mapper_id}}}}; }
json invocation_body(const HookInvocationData& d) { return {{"schema_version", HookInvocation::SCHEMA_VERSION}, {"definition_id", d.definition_id}, {"event_id", d.event_id}, {"target_id", d.target_id}, {"phase", std::string(to_string(d.phase))}, {"delivery", delivery_name(d.delivery)}, {"failure_mode", failure_name(d.failure_mode)}, {"idempotency", idempotency_name(d.idempotency)}, {"effect", effect_name(d.effect)}, {"required_capabilities", capabilities_json(d.required_capabilities)}, {"host_mapper_id", d.host_mapper_id}, {"arguments", d.arguments}}; }
void validate_definition(HookDefinitionData& d) { validate_phase(d.phase); validate_delivery(d.delivery); validate_failure(d.failure_mode); validate_idempotency(d.idempotency); validate_effect(d.effect); if (d.delivery == HookDelivery::BlockingMandatory && d.failure_mode != HookFailureMode::FailClosed) throw std::invalid_argument("Mandatory hooks must fail closed"); detail::validate_token(d.target_id, "Hook target id"); for (const auto& capability : d.required_capabilities) detail::validate_token(capability, "Hook capability"); unsigned nodes = 0; validate_predicate(d.predicate, 0, nodes); validate_mapper(d.input_mapper); }
void validate_invocation(HookInvocationData& d) { validate_phase(d.phase); validate_delivery(d.delivery); validate_failure(d.failure_mode); validate_idempotency(d.idempotency); validate_effect(d.effect); if (d.delivery == HookDelivery::BlockingMandatory && d.failure_mode != HookFailureMode::FailClosed) throw std::invalid_argument("Mandatory hooks must fail closed"); if (!detail::is_sha256_identity(d.definition_id) || !detail::is_sha256_identity(d.event_id)) throw std::invalid_argument("Hook invocation identities are invalid"); detail::validate_token(d.target_id, "Hook invocation target id"); for (const auto& capability : d.required_capabilities) detail::validate_token(capability, "Hook invocation capability"); if (!d.host_mapper_id.empty()) detail::validate_token(d.host_mapper_id, "Hook invocation host mapper id"); d.arguments = canonical_json(d.arguments, "Hook invocation arguments"); }
void validate_target(const HookInvocationData& invocation, const HookTargetContract& target) { if (!target.tool) throw std::invalid_argument("Hook target is not an admitted Tool"); if (!std::includes(target.capabilities.begin(), target.capabilities.end(), invocation.required_capabilities.begin(), invocation.required_capabilities.end())) throw std::invalid_argument("Hook invocation cannot grant target capabilities"); if (target.maximum_effect == ToolEffectClass::Unknown || static_cast<unsigned>(invocation.effect) > static_cast<unsigned>(target.maximum_effect)) throw std::invalid_argument("Hook effect exceeds admitted target contract"); }
std::optional<json> pointer(const RuntimeEvent& event, RuntimeEventField field, std::string_view path) { if (field == RuntimeEventField::Type) return path.empty() ? std::optional<json>(json(event.type())) : std::nullopt; if (field == RuntimeEventField::OwnerScope) return path.empty() ? std::optional<json>(json(event.owner_scope())) : std::nullopt; if (field == RuntimeEventField::RunId) return path.empty() ? std::optional<json>(json(event.run_id())) : std::nullopt; json current = event.data(); if (path.empty()) return current; std::size_t start = 1; while (true) { const auto end = path.find('/', start); const auto raw = path.substr(start, end == std::string_view::npos ? end : end - start); std::string key; for (std::size_t i = 0; i < raw.size(); ++i) { if (raw[i] == '~') { if (++i == raw.size() || (raw[i] != '0' && raw[i] != '1')) return std::nullopt; key += raw[i] == '0' ? '~' : '/'; } else key += raw[i]; } if (current.is_object() && current.contains(key)) current = current[key]; else if (current.is_array()) { try { current = current.at(static_cast<size_t>(std::stoull(key))); } catch (...) { return std::nullopt; } } else return std::nullopt; if (end == std::string_view::npos) return current; start = end + 1; } }
bool matches(const HookPredicate& p, const RuntimeEvent& e) { switch (p.kind) { case HookPredicateKind::True: return true; case HookPredicateKind::All: return std::all_of(p.children.begin(), p.children.end(), [&](const auto& child) { return matches(child, e); }); case HookPredicateKind::Any: return std::any_of(p.children.begin(), p.children.end(), [&](const auto& child) { return matches(child, e); }); case HookPredicateKind::Not: return !matches(p.children.front(), e); case HookPredicateKind::Exists: return pointer(e, p.field, p.pointer).has_value(); case HookPredicateKind::Equals: { const auto found = pointer(e, p.field, p.pointer); return found && *found == p.value; } } return false; }
json map_template(const json& value, const RuntimeEvent& event) { if (value.is_object() && value.contains("$event")) { const auto selected = pointer(event, RuntimeEventField::DataPointer, value["$event"].get<std::string>()); if (!selected) throw std::invalid_argument("Hook input template pointer not found"); return *selected; } if (value.is_array()) { json result = json::array(); for (const auto& child : value) result.push_back(map_template(child, event)); return result; } if (value.is_object()) { json result = json::object(); for (const auto& [key, child] : value.items()) result[key] = map_template(child, event); return result; } return value; }
json map_arguments(const HookInputMapper& mapper, const RuntimeEvent& event) { if (mapper.kind == HookInputMapperKind::JsonPointer) { const auto selected = pointer(event, RuntimeEventField::DataPointer, mapper.json_pointer); if (!selected) throw std::invalid_argument("Hook input pointer not found"); return *selected; } if (mapper.kind == HookInputMapperKind::Template) return map_template(mapper.value_template, event); throw std::invalid_argument("Host mapper requires native execution"); }
} // namespace

std::string_view to_string(HookPhase value) noexcept { switch (value) { case HookPhase::MessageAdmitted: return "message_admitted"; case HookPhase::BeforeProviderRequest: return "before_provider_request"; case HookPhase::AfterProviderResponse: return "after_provider_response"; case HookPhase::BeforeToolExecution: return "before_tool_execution"; case HookPhase::AfterToolExecution: return "after_tool_execution"; case HookPhase::CheckpointPublished: return "checkpoint_published"; case HookPhase::BeforeTerminalPublication: return "before_terminal_publication"; case HookPhase::RunFailed: return "run_failed"; case HookPhase::RunCancelled: return "run_cancelled"; } return "unknown"; }
HookPhase hook_phase_from_string(std::string_view value) { if (value == "message_admitted") return HookPhase::MessageAdmitted; if (value == "before_provider_request") return HookPhase::BeforeProviderRequest; if (value == "after_provider_response") return HookPhase::AfterProviderResponse; if (value == "before_tool_execution") return HookPhase::BeforeToolExecution; if (value == "after_tool_execution") return HookPhase::AfterToolExecution; if (value == "checkpoint_published") return HookPhase::CheckpointPublished; if (value == "before_terminal_publication") return HookPhase::BeforeTerminalPublication; if (value == "run_failed") return HookPhase::RunFailed; if (value == "run_cancelled") return HookPhase::RunCancelled; throw std::invalid_argument("Unknown hook phase"); }
RuntimeEvent RuntimeEvent::create(RuntimeEventData data) { validate_phase(data.phase); detail::validate_token(data.type, "Runtime event type"); detail::validate_token(data.owner_scope, "Runtime event owner scope"); detail::validate_token(data.run_id, "Runtime event run id"); if (!data.sequence) throw std::invalid_argument("Runtime event sequence must be positive"); data.data = canonical_json(data.data, "Runtime event data"); const auto id = digest("runtime-event/v1", event_body(data)); if (!data.event_id.empty() && data.event_id != id) throw std::invalid_argument("Runtime event id mismatch"); data.event_id = id; return RuntimeEvent(std::move(data)); }
RuntimeEvent RuntimeEvent::parse(std::string_view bytes) { const auto value = detail::parse_json_strict(bytes); detail::reject_unknown_fields(value, "Runtime event", {"format", "schema_version", "id", "sequence", "phase", "type", "owner_scope", "run_id", "data"}); if (!value.is_object() || value.at("format").get<std::string>() != "neograph-runtime-event" || value.at("schema_version").get<unsigned>() != SCHEMA_VERSION) throw std::invalid_argument("Unsupported runtime event"); return create({value.at("id").get<std::string>(), value.at("sequence").get<std::uint64_t>(), hook_phase_from_string(value.at("phase").get<std::string>()), value.at("type").get<std::string>(), value.at("owner_scope").get<std::string>(), value.at("run_id").get<std::string>(), value.at("data")}); }
std::string RuntimeEvent::serialize_canonical() const { auto value = event_body(data_); value["format"] = "neograph-runtime-event"; value["id"] = data_.event_id; return detail::canonical_json_bytes(value); }
HookDefinition HookDefinition::create(HookDefinitionData data) { validate_definition(data); const auto id = digest("hook-definition/v1", definition_body(data)); if (!data.definition_id.empty() && data.definition_id != id) throw std::invalid_argument("Hook definition id mismatch"); data.definition_id = id; return HookDefinition(std::move(data)); }
HookDefinition HookDefinition::parse(std::string_view bytes) { const auto value = detail::parse_json_strict(bytes); detail::reject_unknown_fields(value, "Hook definition", {"format", "schema_version", "id", "priority", "phase", "delivery", "failure_mode", "idempotency", "effect", "target_id", "required_capabilities", "predicate", "input_mapper"}); if (!value.is_object() || value.at("format").get<std::string>() != "neograph-hook-definition" || value.at("schema_version").get<unsigned>() != SCHEMA_VERSION) throw std::invalid_argument("Unsupported hook definition"); const auto mapper = value.at("input_mapper"); if (!mapper.is_object()) throw std::invalid_argument("Hook input mapper must be an object"); HookDefinitionData data{value.at("id").get<std::string>(), value.at("priority").get<unsigned>(), hook_phase_from_string(value.at("phase").get<std::string>()), delivery_from_name(value.at("delivery").get<std::string>()), failure_from_name(value.at("failure_mode").get<std::string>()), idem_from_name(value.at("idempotency").get<std::string>()), effect_from_name(value.at("effect").get<std::string>()), value.at("target_id").get<std::string>(), capabilities_from_json(value.at("required_capabilities")), predicate_from_json(value.at("predicate")), {static_cast<HookInputMapperKind>(mapper.at("kind").get<unsigned>()), mapper.at("json_pointer").get<std::string>(), mapper.at("value_template"), mapper.at("host_mapper_id").get<std::string>()}}; return create(std::move(data)); }
std::string HookDefinition::serialize_canonical() const { auto value = definition_body(data_); value["format"] = "neograph-hook-definition"; value["id"] = data_.definition_id; return detail::canonical_json_bytes(value); }
HookInvocation HookInvocation::create(HookInvocationData data) { validate_invocation(data); const auto id = digest("hook-invocation/v1", invocation_body(data)); if (!data.invocation_id.empty() && data.invocation_id != id) throw std::invalid_argument("Hook invocation id mismatch"); data.invocation_id = id; return HookInvocation(std::move(data)); }
HookInvocation HookInvocation::parse(std::string_view bytes) { const auto value = detail::parse_json_strict(bytes); detail::reject_unknown_fields(value, "Hook invocation", {"format", "schema_version", "id", "definition_id", "event_id", "target_id", "phase", "delivery", "failure_mode", "idempotency", "effect", "required_capabilities", "host_mapper_id", "arguments"}); if (!value.is_object() || value.at("format").get<std::string>() != "neograph-hook-invocation" || value.at("schema_version").get<unsigned>() != SCHEMA_VERSION) throw std::invalid_argument("Unsupported hook invocation"); return create({value.at("id").get<std::string>(), value.at("definition_id").get<std::string>(), value.at("event_id").get<std::string>(), value.at("target_id").get<std::string>(), hook_phase_from_string(value.at("phase").get<std::string>()), delivery_from_name(value.at("delivery").get<std::string>()), failure_from_name(value.at("failure_mode").get<std::string>()), idem_from_name(value.at("idempotency").get<std::string>()), effect_from_name(value.at("effect").get<std::string>()), capabilities_from_json(value.at("required_capabilities")), value.at("host_mapper_id").get<std::string>(), value.at("arguments")}); }
std::string HookInvocation::serialize_canonical() const { auto value = invocation_body(data_); value["format"] = "neograph-hook-invocation"; value["id"] = data_.invocation_id; return detail::canonical_json_bytes(value); }
HookRegistry::HookRegistry(HookTargetResolver resolver, std::set<std::string> mapper_ids) : target_resolver_(std::move(resolver)), admitted_host_mapper_ids_(std::move(mapper_ids)) { if (!target_resolver_) throw std::invalid_argument("Hook target resolver is required"); for (const auto& id : admitted_host_mapper_ids_) detail::validate_token(id, "Hook host mapper id"); }
void HookRegistry::admit(HookDefinition definition) { const auto target = target_resolver_(definition.data().target_id); if (!target) throw std::invalid_argument("Hook target is not admitted"); HookInvocationData invocation; invocation.definition_id = definition.id(); invocation.event_id = "sha256:" + std::string(64, '0'); invocation.target_id = definition.data().target_id; invocation.phase = definition.data().phase; invocation.delivery = definition.data().delivery; invocation.failure_mode = definition.data().failure_mode; invocation.idempotency = definition.data().idempotency; invocation.effect = definition.data().effect; invocation.required_capabilities = definition.data().required_capabilities; invocation.host_mapper_id = definition.data().input_mapper.host_mapper_id; validate_invocation(invocation); validate_target(invocation, *target); if (definition.data().input_mapper.kind == HookInputMapperKind::HostMapper && !admitted_host_mapper_ids_.count(definition.data().input_mapper.host_mapper_id)) throw std::invalid_argument("Hook host mapper is not admitted"); definitions_.push_back(std::move(definition)); std::sort(definitions_.begin(), definitions_.end(), [](const auto& a, const auto& b) { return std::tie(a.data().priority, a.id()) < std::tie(b.data().priority, b.id()); }); }
std::vector<HookInvocation> HookRegistry::plan(const RuntimeEvent& event) const { std::vector<HookInvocation> result; for (const auto& definition : definitions_) { if (definition.data().phase != event.phase() || !matches(definition.data().predicate, event)) continue; const auto arguments = definition.data().input_mapper.kind == HookInputMapperKind::HostMapper ? json::object() : canonical_json(map_arguments(definition.data().input_mapper, event), "Hook mapped arguments"); result.push_back(HookInvocation::create({{}, definition.id(), event.id(), definition.data().target_id, definition.data().phase, definition.data().delivery, definition.data().failure_mode, definition.data().idempotency, definition.data().effect, definition.data().required_capabilities, definition.data().input_mapper.host_mapper_id, arguments})); } return result; }
NativeHookExecutionAdapter::NativeHookExecutionAdapter(HookTargetResolver resolver, std::shared_ptr<ToolExecutionController> controller, HookHostMapper mapper, std::set<std::string> mapper_ids) : target_resolver_(std::move(resolver)), controller_(std::move(controller)), host_mapper_(std::move(mapper)), admitted_host_mapper_ids_(std::move(mapper_ids)) { if (!target_resolver_ || !controller_) throw std::invalid_argument("Hook execution requires a resolver and controller"); for (const auto& id : admitted_host_mapper_ids_) detail::validate_token(id, "Hook host mapper id"); }
asio::awaitable<ToolExecutionResult> NativeHookExecutionAdapter::execute_result_async(const HookInvocation& invocation, const RuntimeEvent& event, ToolExecutionContext context) const { if (invocation.data().event_id != event.id() || invocation.data().phase != event.phase()) throw std::invalid_argument("Hook invocation does not match runtime event"); const auto target = target_resolver_(invocation.data().target_id); if (!target) throw std::invalid_argument("Hook target is not admitted"); validate_target(invocation.data(), *target); auto arguments = invocation.data().arguments; if (!invocation.data().host_mapper_id.empty()) { if (!host_mapper_ || !admitted_host_mapper_ids_.count(invocation.data().host_mapper_id)) throw std::invalid_argument("Hook host mapper is not admitted"); arguments = canonical_json(host_mapper_(invocation.data().host_mapper_id, event), "Hook host mapper output"); } if (context.identity.request_id.empty()) context.identity.request_id = invocation.id(); context.controller = controller_; co_return co_await controller_->execute_result_async(*target->tool, std::move(arguments), std::move(context)); }
} // namespace neograph
