#include <neograph/hook_outbox.h>

#include "canonical_json.h"

#include <algorithm>
#include <mutex>
#include <unordered_map>

namespace neograph { namespace {
using Clock = std::chrono::system_clock;
bool valid(HookExecutionState s) { return static_cast<unsigned>(s) <= static_cast<unsigned>(HookExecutionState::Cancelled); }
bool terminal(HookExecutionState s) { return s == HookExecutionState::Succeeded || s == HookExecutionState::TimedOut || s == HookExecutionState::ReconciliationRequired || s == HookExecutionState::Cancelled; }
std::int64_t ms(Clock::time_point t) { return std::chrono::duration_cast<std::chrono::milliseconds>(t.time_since_epoch()).count(); }
Clock::time_point time(std::int64_t value) { return Clock::time_point(std::chrono::milliseconds(value)); }
void identity(std::string_view v) { if (!detail::is_sha256_identity(v)) throw std::invalid_argument("invalid hook invocation identity"); }
std::string digest(std::string_view domain, const json& value) { return detail::sha256_identity("NeoGraph Hook outbox v1", domain, detail::canonical_json_bytes(value)); }
json external(const ExternalEffectReceipt& r) { return {{"receipt_id", r.receipt_id}, {"outcome_known", r.outcome_known}, {"succeeded", r.succeeded}, {"detail", r.detail}}; }
ExternalEffectReceipt external_from(const json& v) { detail::reject_unknown_fields(v, "Hook external effect receipt", {"receipt_id", "outcome_known", "succeeded", "detail"}); return {v.at("receipt_id").get<std::string>(), v.at("outcome_known").get<bool>(), v.at("succeeded").get<bool>(), v.at("detail").get<std::string>()}; }
HookExecutionState state_from(std::string_view v) { for (unsigned i = 0; i <= static_cast<unsigned>(HookExecutionState::Cancelled); ++i) { const auto s = static_cast<HookExecutionState>(i); if (to_string(s) == v) return s; } throw std::invalid_argument("unknown hook execution state"); }
json receipt_body(const HookExecutionReceiptData& d) { return {{"schema_version", 1}, {"invocation_id", d.invocation_id}, {"attempt", d.attempt}, {"state", std::string(to_string(d.state))}, {"external_effect", external(d.external_effect)}, {"error", d.error}}; }
json receipt_json(const HookExecutionReceipt& r) { auto v = receipt_body(r.data()); v["format"] = "neograph-hook-execution-receipt"; v["id"] = r.id(); return v; }
HookExecutionReceipt receipt_from(const json& v) { detail::reject_unknown_fields(v, "Hook execution receipt", {"format", "schema_version", "id", "invocation_id", "attempt", "state", "external_effect", "error"}); if (v.at("format") != "neograph-hook-execution-receipt" || v.at("schema_version") != 1) throw std::invalid_argument("unsupported hook execution receipt"); auto r = HookExecutionReceipt::create({v.at("invocation_id").get<std::string>(), v.at("attempt").get<std::uint32_t>(), state_from(v.at("state").get<std::string>()), external_from(v.at("external_effect")), v.at("error").get<std::string>()}); if (v.at("id").get<std::string>() != r.id()) throw std::invalid_argument("hook receipt id mismatch"); return r; }
json entry_body(const HookOutboxEntryData& d) { return {{"schema_version", 1}, {"invocation", d.invocation.serialize_canonical()}, {"event", d.event.serialize_canonical()}, {"state", std::string(to_string(d.state))}, {"attempt_count", d.attempt_count}, {"max_attempts", d.max_attempts}, {"deadline_ms", ms(d.deadline)}, {"fencing_token", d.fencing_token}, {"lease_expires_at_ms", ms(d.lease_expires_at)}, {"receipt", d.receipt ? receipt_json(*d.receipt) : json(nullptr)}}; }
HookExecutionReceipt failed_receipt(const HookOutboxEntry& e, std::string error) { return HookExecutionReceipt::create({e.data().invocation.id(), e.data().attempt_count, HookExecutionState::Failed, {}, std::move(error)}); }
HookExecutionReceipt result_receipt(const HookOutboxEntry& e, const ToolExecutionResult& r) {
    const auto& invocation = e.data().invocation;
    const auto detail = r.output.substr(0, 4096);
    if (r.succeeded()) {
        const auto receipt_id = digest("native-hook-effect/v1",
            json{{"invocation_id", invocation.id()}, {"attempt", e.data().attempt_count}});
        return HookExecutionReceipt::create({invocation.id(), e.data().attempt_count,
            HookExecutionState::Succeeded, {receipt_id, true, true, detail}, {}});
    }
    const bool ambiguous = r.effect_uncertain || r.status == ToolTerminalStatus::ReconciliationRequired;
    const auto state = ambiguous && invocation.data().idempotency == HookIdempotency::NonIdempotent
        ? HookExecutionState::ReconciliationRequired
        : (r.status == ToolTerminalStatus::CancelledBeforeStart ||
           r.status == ToolTerminalStatus::CancellationRequested
               ? HookExecutionState::Cancelled : HookExecutionState::Failed);
    return HookExecutionReceipt::create({invocation.id(), e.data().attempt_count, state, {},
        r.error.empty() ? "adapter supplied no known external effect receipt" : r.error.substr(0, 4096)});
}
} // namespace

std::string_view to_string(HookExecutionState v) noexcept { switch (v) { case HookExecutionState::Triggered: return "triggered"; case HookExecutionState::Pending: return "pending"; case HookExecutionState::Dispatched: return "dispatched"; case HookExecutionState::Succeeded: return "succeeded"; case HookExecutionState::Failed: return "failed"; case HookExecutionState::TimedOut: return "timed_out"; case HookExecutionState::ReconciliationRequired: return "reconciliation_required"; case HookExecutionState::Cancelled: return "cancelled"; } return "unknown"; }
HookExecutionReceipt HookExecutionReceipt::create(HookExecutionReceiptData d) { identity(d.invocation_id); if (!d.attempt || !valid(d.state) || d.state == HookExecutionState::Triggered || d.state == HookExecutionState::Pending || d.state == HookExecutionState::Dispatched || (d.state == HookExecutionState::Succeeded && (!d.external_effect.outcome_known || !d.external_effect.succeeded || d.external_effect.receipt_id.empty())) || d.external_effect.receipt_id.size() > 4096 || d.error.size() > 4096) throw std::invalid_argument("invalid hook execution receipt"); HookExecutionReceipt r(std::move(d)); r.id_ = digest("execution-receipt/v1", receipt_body(r.data_)); return r; }
HookExecutionReceipt HookExecutionReceipt::parse(std::string_view b) { return receipt_from(detail::parse_json_strict(b)); }
std::string HookExecutionReceipt::serialize_canonical() const { return detail::canonical_json_bytes(receipt_json(*this)); }
HookOutboxEntry HookOutboxEntry::create(HookOutboxEntryData d) { const bool lease = d.lease_expires_at != Clock::time_point{}; if (d.invocation.data().event_id != d.event.id() || d.invocation.data().phase != d.event.phase() || !valid(d.state) || !d.max_attempts || d.max_attempts > 1000 || d.attempt_count > d.max_attempts || d.deadline == Clock::time_point{} || (d.receipt && (d.receipt->data().invocation_id != d.invocation.id() || d.receipt->data().attempt != d.attempt_count))) throw std::invalid_argument("invalid hook outbox entry"); if (d.state == HookExecutionState::Triggered || d.state == HookExecutionState::Pending) { if (d.attempt_count || d.fencing_token || lease || d.receipt) throw std::invalid_argument("unattempted hook state has execution data"); } else if (d.state == HookExecutionState::Dispatched) { if (!d.attempt_count || !d.fencing_token || !lease || d.lease_expires_at > d.deadline || d.receipt) throw std::invalid_argument("dispatched hook requires a bounded lease"); } else { const bool attempted = d.attempt_count && d.fencing_token; const bool success = d.state == HookExecutionState::Succeeded; const bool failed = d.state == HookExecutionState::Failed; const bool reconcile = d.state == HookExecutionState::ReconciliationRequired; const bool cancelled = d.state == HookExecutionState::Cancelled; if (lease || (success && (!attempted || !d.receipt || d.receipt->data().state != HookExecutionState::Succeeded)) || (failed && (!attempted || !d.receipt || d.receipt->data().state != HookExecutionState::Failed)) || (reconcile && (!attempted || !d.receipt || d.receipt->data().state != HookExecutionState::ReconciliationRequired)) || (cancelled && (!attempted || !d.receipt || d.receipt->data().state != HookExecutionState::Cancelled)) || (d.state == HookExecutionState::TimedOut && d.receipt && d.receipt->data().state != HookExecutionState::Failed && d.receipt->data().state != HookExecutionState::TimedOut)) throw std::invalid_argument("terminal hook state has invalid receipt or lease"); } HookOutboxEntry e(std::move(d)); e.id_ = digest("outbox-entry/v1", entry_body(e.data_)); return e; }
HookOutboxEntry HookOutboxEntry::parse(std::string_view b) { auto v = detail::parse_json_strict(b); detail::reject_unknown_fields(v, "Hook outbox entry", {"format", "schema_version", "id", "invocation", "event", "state", "attempt_count", "max_attempts", "deadline_ms", "fencing_token", "lease_expires_at_ms", "receipt"}); if (v.at("format") != "neograph-hook-outbox-entry" || v.at("schema_version") != 1) throw std::invalid_argument("unsupported hook outbox entry"); std::optional<HookExecutionReceipt> r; if (!v.at("receipt").is_null()) r = receipt_from(v.at("receipt")); auto e = create({HookInvocation::parse(v.at("invocation").get<std::string>()), RuntimeEvent::parse(v.at("event").get<std::string>()), state_from(v.at("state").get<std::string>()), v.at("attempt_count").get<std::uint32_t>(), v.at("max_attempts").get<std::uint32_t>(), time(v.at("deadline_ms").get<std::int64_t>()), v.at("fencing_token").get<std::uint64_t>(), time(v.at("lease_expires_at_ms").get<std::int64_t>()), std::move(r)}); if (v.at("id").get<std::string>() != e.id()) throw std::invalid_argument("hook outbox entry id mismatch"); return e; }
std::string HookOutboxEntry::serialize_canonical() const { auto v = entry_body(data_); v["format"] = "neograph-hook-outbox-entry"; v["id"] = id_; return detail::canonical_json_bytes(v); }
HookBoundaryBlocked::HookBoundaryBlocked(std::string id, HookExecutionState s, std::string message) : std::runtime_error(std::move(message)), invocation_id_(std::move(id)), state_(s) {}

class InMemoryHookJournal::Impl { public: mutable std::mutex mu; std::unordered_map<std::string, HookOutboxEntry> entries; };
InMemoryHookJournal::InMemoryHookJournal() : impl_(std::make_unique<Impl>()) {} InMemoryHookJournal::~InMemoryHookJournal() = default;
HookOutboxEntry InMemoryHookJournal::enqueue(HookInvocation i, RuntimeEvent e, std::uint32_t max, Clock::time_point deadline) { auto candidate = HookOutboxEntry::create({std::move(i), std::move(e), HookExecutionState::Triggered, 0, max, deadline}); std::lock_guard<std::mutex> lock(impl_->mu); auto [it, inserted] = impl_->entries.emplace(candidate.data().invocation.id(), candidate); if (!inserted && (it->second.data().invocation.serialize_canonical() != candidate.data().invocation.serialize_canonical() || it->second.data().event.serialize_canonical() != candidate.data().event.serialize_canonical() || it->second.data().max_attempts != max || it->second.data().deadline != deadline)) throw std::invalid_argument("logical hook invocation enqueue conflict"); return it->second; }
HookOutboxEntry InMemoryHookJournal::publish(std::string_view id) { std::lock_guard<std::mutex> lock(impl_->mu); auto it = impl_->entries.find(std::string(id)); if (it == impl_->entries.end()) throw std::out_of_range("hook invocation is not enqueued"); auto d = it->second.data(); if (d.state == HookExecutionState::Triggered) { d.state = HookExecutionState::Pending; it->second = HookOutboxEntry::create(std::move(d)); } return it->second; }
std::optional<HookLease> InMemoryHookJournal::claim(std::string_view id, std::string_view worker, Clock::time_point now, std::chrono::milliseconds duration) { if (worker.empty() || duration <= std::chrono::milliseconds::zero()) throw std::invalid_argument("invalid hook claim"); std::lock_guard<std::mutex> lock(impl_->mu); auto it = impl_->entries.find(std::string(id)); if (it == impl_->entries.end()) return std::nullopt; auto d = it->second.data(); if (d.deadline <= now && !terminal(d.state)) { d.state = HookExecutionState::TimedOut; d.lease_expires_at = {}; it->second = HookOutboxEntry::create(std::move(d)); return std::nullopt; } if (d.state == HookExecutionState::Dispatched && d.lease_expires_at <= now) { if (d.invocation.data().idempotency == HookIdempotency::NonIdempotent) { d.state = HookExecutionState::ReconciliationRequired; d.lease_expires_at = {}; d.receipt = HookExecutionReceipt::create({d.invocation.id(), d.attempt_count, HookExecutionState::ReconciliationRequired, {}, "non-idempotent dispatched lease expired; external outcome is unknown"}); it->second = HookOutboxEntry::create(std::move(d)); return std::nullopt; } d.state = HookExecutionState::Failed; d.lease_expires_at = {}; d.receipt = HookExecutionReceipt::create({d.invocation.id(), d.attempt_count, HookExecutionState::Failed, {}, "idempotent dispatched lease expired"}); it->second = HookOutboxEntry::create(std::move(d)); d = it->second.data(); } if (d.state != HookExecutionState::Pending && !(d.state == HookExecutionState::Failed && d.attempt_count < d.max_attempts)) return std::nullopt; if (d.attempt_count >= d.max_attempts) { d.state = HookExecutionState::TimedOut; it->second = HookOutboxEntry::create(std::move(d)); return std::nullopt; } d.state = HookExecutionState::Dispatched; ++d.attempt_count; ++d.fencing_token; d.receipt.reset(); d.lease_expires_at = std::min(d.deadline, now + duration); it->second = HookOutboxEntry::create(std::move(d)); return HookLease{it->second, it->second.data().fencing_token}; }
std::optional<HookOutboxEntry> InMemoryHookJournal::settle(std::string_view id, std::uint64_t fence, HookExecutionReceipt receipt, Clock::time_point now) { std::lock_guard<std::mutex> lock(impl_->mu); auto it = impl_->entries.find(std::string(id)); if (it == impl_->entries.end()) return std::nullopt; auto d = it->second.data(); if (d.state != HookExecutionState::Dispatched || d.fencing_token != fence || d.lease_expires_at < now || receipt.data().invocation_id != id || receipt.data().attempt != d.attempt_count) return std::nullopt; d.receipt = std::move(receipt); d.state = d.receipt->data().state; d.lease_expires_at = {}; if (d.state == HookExecutionState::Failed && d.attempt_count >= d.max_attempts) d.state = HookExecutionState::TimedOut; it->second = HookOutboxEntry::create(std::move(d)); return it->second; }
std::optional<HookOutboxEntry> InMemoryHookJournal::reconcile(std::string_view id, HookExecutionState expected, std::string_view head, std::uint64_t fence, HookExecutionReceipt known) { std::lock_guard<std::mutex> lock(impl_->mu); auto it = impl_->entries.find(std::string(id)); if (it == impl_->entries.end() || it->second.data().state != expected || it->second.id() != head || it->second.data().fencing_token != fence || expected != HookExecutionState::ReconciliationRequired || !known.data().external_effect.outcome_known || known.data().invocation_id != id || known.data().attempt != it->second.data().attempt_count || (known.data().state != HookExecutionState::Succeeded && known.data().state != HookExecutionState::Failed)) return std::nullopt; auto d = it->second.data(); d.state = known.data().state; d.receipt = std::move(known); it->second = HookOutboxEntry::create(std::move(d)); return it->second; }
std::vector<HookOutboxEntry> InMemoryHookJournal::pending() const { std::lock_guard<std::mutex> lock(impl_->mu); std::vector<HookOutboxEntry> r; for (const auto& [_, e] : impl_->entries) if (e.data().state == HookExecutionState::Triggered || e.data().state == HookExecutionState::Pending || e.data().state == HookExecutionState::Failed || e.data().state == HookExecutionState::Dispatched) r.push_back(e); return r; }
std::vector<HookOutboxEntry> InMemoryHookJournal::reconciliation_required() const { std::lock_guard<std::mutex> lock(impl_->mu); std::vector<HookOutboxEntry> r; for (const auto& [_, e] : impl_->entries) if (e.data().state == HookExecutionState::ReconciliationRequired) r.push_back(e); return r; }
std::optional<HookOutboxEntry> InMemoryHookJournal::get(std::string_view id) const { std::lock_guard<std::mutex> lock(impl_->mu); auto it = impl_->entries.find(std::string(id)); return it == impl_->entries.end() ? std::nullopt : std::optional<HookOutboxEntry>(it->second); }

MandatoryHookRunner::MandatoryHookRunner(std::shared_ptr<HookJournal> journal, std::shared_ptr<const HookRegistry> registry, std::shared_ptr<const NativeHookExecutionAdapter> adapter, std::string worker) : journal_(std::move(journal)), registry_(std::move(registry)), adapter_(std::move(adapter)), worker_id_(std::move(worker)) { if (!journal_ || !registry_ || !adapter_ || worker_id_.empty()) throw std::invalid_argument("hook runner requires durable dependencies and a worker identity"); }
asio::awaitable<void> MandatoryHookRunner::run_async(const RuntimeEvent& event, Clock::time_point deadline, std::uint32_t max_attempts) { if (deadline <= Clock::now() || !max_attempts) throw std::invalid_argument("invalid hook execution deadline"); for (const auto& invocation : registry_->plan(event)) { auto entry = journal_->enqueue(invocation, event, max_attempts, deadline); entry = journal_->publish(invocation.id()); for (;;) { const auto now = Clock::now(); if (now >= deadline) { entry = journal_->get(invocation.id()).value_or(entry); if (invocation.data().delivery == HookDelivery::BlockingMandatory) throw HookBoundaryBlocked(invocation.id(), entry.data().state, "mandatory hook deadline elapsed"); break; } const auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(deadline - now); auto lease = journal_->claim(invocation.id(), worker_id_, now, std::min(std::chrono::milliseconds(30'000), remaining)); if (!lease) { entry = journal_->get(invocation.id()).value_or(entry); } else { ToolExecutionContext context; context.identity.request_id = invocation.id(); context.identity.root_run_id = event.run_id(); context.identity.thread_id = "hook-fence:" + std::to_string(lease->fencing_token); context.deadline = std::chrono::steady_clock::now() + std::chrono::duration_cast<std::chrono::steady_clock::duration>(deadline - Clock::now()); try { const auto result = co_await adapter_->execute_result_async(invocation, event, std::move(context)); const auto settled = journal_->settle(invocation.id(), lease->fencing_token, result_receipt(lease->entry, result), Clock::now()); if (!settled) { entry = journal_->get(invocation.id()).value_or(lease->entry); if (invocation.data().delivery == HookDelivery::BlockingMandatory) throw HookBoundaryBlocked(invocation.id(), entry.data().state, "hook settlement lost ownership"); break; } entry = *settled; } catch (const HookBoundaryBlocked&) { throw; } catch (const std::exception& error) { const auto settled = journal_->settle(invocation.id(), lease->fencing_token, failed_receipt(lease->entry, error.what()), Clock::now()); if (!settled) { entry = journal_->get(invocation.id()).value_or(lease->entry); if (invocation.data().delivery == HookDelivery::BlockingMandatory) throw HookBoundaryBlocked(invocation.id(), entry.data().state, "hook settlement lost ownership"); break; } entry = *settled; } }
            if (entry.data().state == HookExecutionState::Succeeded) break;
            if (entry.data().state == HookExecutionState::Failed && entry.data().attempt_count < entry.data().max_attempts && Clock::now() < deadline) continue;
            if (invocation.data().delivery == HookDelivery::BlockingMandatory) throw HookBoundaryBlocked(invocation.id(), entry.data().state, "mandatory hook did not settle successfully");
            break;
        }
    } co_return;
}
} // namespace neograph
