#include <neograph/sqlite_runtime_stores.h>
#include "canonical_json.h"
#include <sqlite3.h>
#include <algorithm>
#include <limits>
#include <mutex>
#include <stdexcept>

namespace neograph { namespace {
using Clock = std::chrono::system_clock;
[[noreturn]] void fail(sqlite3* db, std::string_view what) { throw std::runtime_error("SQLite runtime store " + std::string(what) + ": " + (db ? sqlite3_errmsg(db) : "unavailable")); }
void exec(sqlite3* db, const char* sql) { char* error = nullptr; if (sqlite3_exec(db, sql, nullptr, nullptr, &error) != SQLITE_OK) { std::string message = error ? error : sqlite3_errmsg(db); sqlite3_free(error); throw std::runtime_error("SQLite runtime store schema: " + message); } }
class Stmt { public: Stmt(sqlite3* d, const char* s): db(d) { if(sqlite3_prepare_v2(d,s,-1,&p,nullptr)!=SQLITE_OK) fail(d,"prepare"); } ~Stmt(){sqlite3_finalize(p);} void text(int i,std::string_view v){if(v.size()>static_cast<size_t>(std::numeric_limits<int>::max()))throw std::overflow_error("SQLite text bind exceeds INT_MAX");if(sqlite3_bind_text(p,i,v.data(),static_cast<int>(v.size()),SQLITE_TRANSIENT)!=SQLITE_OK)fail(db,"bind");} void i64(int i,std::uint64_t v){if(v>static_cast<std::uint64_t>(std::numeric_limits<sqlite3_int64>::max()))throw std::overflow_error("SQLite integer overflow");if(sqlite3_bind_int64(p,i,static_cast<sqlite3_int64>(v))!=SQLITE_OK)fail(db,"bind");} bool row(){int r=sqlite3_step(p);if(r==SQLITE_ROW)return true;if(r==SQLITE_DONE)return false;fail(db,"step");} void done(){if(sqlite3_step(p)!=SQLITE_DONE)fail(db,"step");} sqlite3_stmt* get(){return p;} private:sqlite3* db;sqlite3_stmt* p=nullptr;};
class Tx { public: explicit Tx(sqlite3* d):db(d){exec(db,"BEGIN IMMEDIATE");} ~Tx(){if(!ok){char* e=nullptr;sqlite3_exec(db,"ROLLBACK",nullptr,nullptr,&e);sqlite3_free(e);}} void commit(){exec(db,"COMMIT");ok=true;} private:sqlite3* db;bool ok=false;};
std::string bytes(sqlite3_stmt* s,int i){auto p=static_cast<const char*>(sqlite3_column_blob(s,i));int n=sqlite3_column_bytes(s,i);if(!p||n<0)throw std::runtime_error("SQLite runtime store has null canonical bytes");return {p,static_cast<size_t>(n)};}
std::string text(sqlite3_stmt* s,int i){auto p=reinterpret_cast<const char*>(sqlite3_column_text(s,i));int n=sqlite3_column_bytes(s,i);if(!p||n<0)throw std::runtime_error("SQLite runtime store has null text");return {p,static_cast<size_t>(n)};}
void open(sqlite3*& db,const std::string& path){if(path.empty())throw std::invalid_argument("SQLite runtime store path must not be empty");if(sqlite3_open_v2(path.c_str(),&db,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK)fail(db,"open");try{exec(db,"PRAGMA journal_mode=WAL");exec(db,"PRAGMA synchronous=FULL");exec(db,"PRAGMA foreign_keys=ON");exec(db,"PRAGMA busy_timeout=5000");Tx tx(db);exec(db,"CREATE TABLE IF NOT EXISTS ng_runtime_store_schema(version INTEGER NOT NULL)");Stmt v(db,"SELECT version FROM ng_runtime_store_schema");const auto version=v.row()?sqlite3_column_int(v.get(),0):0;if(version>2)throw std::runtime_error("SQLite runtime store schema is newer than this library");exec(db,"CREATE TABLE IF NOT EXISTS ng_runtime_history(owner_id TEXT NOT NULL,feed_id TEXT NOT NULL,sequence INTEGER NOT NULL,record_id TEXT NOT NULL,canonical BLOB NOT NULL,PRIMARY KEY(owner_id,feed_id,sequence))");exec(db,"CREATE UNIQUE INDEX IF NOT EXISTS ng_runtime_history_identity ON ng_runtime_history(owner_id,feed_id,record_id)");exec(db,"CREATE TABLE IF NOT EXISTS ng_runtime_artifacts(owner_id TEXT NOT NULL,artifact_id TEXT NOT NULL,canonical BLOB NOT NULL,PRIMARY KEY(owner_id,artifact_id))");exec(db,"CREATE TABLE IF NOT EXISTS ng_hook_outbox(invocation_id TEXT PRIMARY KEY NOT NULL,canonical BLOB NOT NULL,state INTEGER NOT NULL)");exec(db,"CREATE INDEX IF NOT EXISTS ng_hook_outbox_state ON ng_hook_outbox(state)");if(version==1){exec(db,"CREATE TABLE ng_provider_receipts_v2(owner_scope TEXT NOT NULL,dispatch_id TEXT NOT NULL,canonical BLOB NOT NULL,PRIMARY KEY(owner_scope,dispatch_id))");exec(db,"INSERT INTO ng_provider_receipts_v2 SELECT '',dispatch_id,canonical FROM ng_provider_receipts");exec(db,"DROP TABLE ng_provider_receipts");exec(db,"ALTER TABLE ng_provider_receipts_v2 RENAME TO ng_provider_receipts");exec(db,"UPDATE ng_runtime_store_schema SET version=2");}else{exec(db,"CREATE TABLE IF NOT EXISTS ng_provider_receipts(owner_scope TEXT NOT NULL,dispatch_id TEXT NOT NULL,canonical BLOB NOT NULL,PRIMARY KEY(owner_scope,dispatch_id))");if(!version)exec(db,"INSERT INTO ng_runtime_store_schema VALUES(2)");}tx.commit();}catch(...){sqlite3_close_v2(db);db=nullptr;throw;}}
void validate_owner(std::string_view owner){if(owner.empty()||owner.size()>InMemoryContextStore::MAX_OWNER_ID_BYTES)throw std::invalid_argument("Context store owner_id is invalid");detail::validate_token(owner,"Context store owner_id");}
void validate_receipt_owner(std::string_view owner){if(!owner.empty())validate_owner(owner);}
void validate_feed(const ContextStoreFeed& f){validate_owner(f.owner_id);if(f.feed_id.empty()||f.feed_id.size()>InMemoryContextStore::MAX_FEED_ID_BYTES)throw std::invalid_argument("Context store feed_id is invalid");detail::validate_token(f.feed_id,"Context store feed_id");}
constexpr std::string_view PRE="NeoGraph Context history range v1", DOMAIN="context-history-range-jsonl/v1", REF="context-history-range-reference/v1";
std::string digest(std::string_view s){return detail::sha256_identity(PRE,DOMAIN,s);} std::string uri(const ContextHistoryRange& r){return "neograph://context/history/"+detail::sha256_identity(PRE,REF,detail::canonical_json_bytes(json{{"owner_id",r.owner_id},{"feed_id",r.feed_id},{"from_sequence",r.from_sequence},{"through_sequence",r.through_sequence},{"digest",r.digest}})).substr(7);}
bool terminal(HookExecutionState s){return s==HookExecutionState::Succeeded||s==HookExecutionState::TimedOut||s==HookExecutionState::ReconciliationRequired||s==HookExecutionState::Cancelled;}
HookOutboxEntry checked_hook(std::string_view id,sqlite3_int64 state,std::string_view canonical){auto entry=HookOutboxEntry::parse(canonical);if(entry.data().invocation.id()!=id||entry.data().state!=static_cast<HookExecutionState>(state))throw std::runtime_error("SQLite hook entry key or state mismatches canonical data");return entry;}
std::optional<HookOutboxEntry> hook(sqlite3* db,std::string_view id){Stmt s(db,"SELECT canonical,state FROM ng_hook_outbox WHERE invocation_id=?1");s.text(1,id);if(!s.row())return std::nullopt;auto canonical=bytes(s.get(),0);return checked_hook(id,sqlite3_column_int64(s.get(),1),canonical);}
void save_hook(sqlite3* db,const HookOutboxEntry& e){Stmt s(db,"UPDATE ng_hook_outbox SET canonical=?2,state=?3 WHERE invocation_id=?1");s.text(1,e.data().invocation.id());s.text(2,e.serialize_canonical());s.i64(3,static_cast<unsigned>(e.data().state));s.done();if(sqlite3_changes(db)!=1)throw std::runtime_error("SQLite hook entry disappeared during update");}
}
struct SQLiteContextStore::Impl { explicit Impl(std::string p){open(db,p);} ~Impl(){if(db)sqlite3_close_v2(db);} sqlite3* db=nullptr;mutable std::mutex mu;};
SQLiteContextStore::SQLiteContextStore(std::string p):impl_(std::make_unique<Impl>(std::move(p))){} SQLiteContextStore::~SQLiteContextStore()=default; SQLiteContextStore::SQLiteContextStore(SQLiteContextStore&&) noexcept=default; SQLiteContextStore& SQLiteContextStore::operator=(SQLiteContextStore&&) noexcept=default;
ContextStoreAppendResult SQLiteContextStore::append_history(const ContextStoreFeed& f,const RuntimeHistoryRecord& r,const std::optional<std::string>& expected){validate_feed(f);if(r.feed_id()!=f.feed_id)throw std::invalid_argument("record does not belong to feed");if(expected&&!detail::is_sha256_identity(*expected))throw std::invalid_argument("invalid expected head");auto canonical=r.serialize_canonical();if(canonical.size()>InMemoryContextStore::MAX_RECORD_BYTES)throw std::invalid_argument("record too large");std::lock_guard l(impl_->mu);Tx tx(impl_->db);Stmt old(impl_->db,"SELECT canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 AND sequence=?3");old.text(1,f.owner_id);old.text(2,f.feed_id);old.i64(3,r.sequence());if(old.row()){const auto stored=bytes(old.get(),0);const auto parsed=RuntimeHistoryRecord::parse(stored);if(parsed.feed_id()!=f.feed_id||parsed.sequence()!=r.sequence())throw std::runtime_error("corrupt history record metadata");auto same=stored==canonical;tx.commit();return same?ContextStoreAppendResult::AlreadyPresent:ContextStoreAppendResult::Conflict;} Stmt head(impl_->db,"SELECT sequence,record_id,canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 ORDER BY sequence DESC LIMIT 1");head.text(1,f.owner_id);head.text(2,f.feed_id);std::uint64_t seq=0;std::string id;if(head.row()){auto n=sqlite3_column_int64(head.get(),0);if(n<1)throw std::runtime_error("corrupt history sequence");seq=static_cast<std::uint64_t>(n);id=text(head.get(),1);const auto parsed=RuntimeHistoryRecord::parse(bytes(head.get(),2));if(parsed.feed_id()!=f.feed_id||parsed.sequence()!=seq||parsed.id()!=id)throw std::runtime_error("corrupt history head");}if(r.sequence()!=seq+1||(expected?*expected:"")!=id||(r.sequence()==1?r.predecessor_id().has_value():!r.predecessor_id()||*r.predecessor_id()!=id)){tx.commit();return ContextStoreAppendResult::Conflict;}Stmt put(impl_->db,"INSERT INTO ng_runtime_history VALUES(?1,?2,?3,?4,?5)");put.text(1,f.owner_id);put.text(2,f.feed_id);put.i64(3,r.sequence());put.text(4,r.id());put.text(5,canonical);put.done();tx.commit();return ContextStoreAppendResult::Appended;}
ContextStoreHead SQLiteContextStore::history_head(const ContextStoreFeed& f)const{validate_feed(f);std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT sequence,record_id,canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 ORDER BY sequence DESC LIMIT 1");s.text(1,f.owner_id);s.text(2,f.feed_id);if(!s.row())return {};auto n=sqlite3_column_int64(s.get(),0);if(n<1)throw std::runtime_error("corrupt history sequence");auto id=text(s.get(),1);auto parsed=RuntimeHistoryRecord::parse(bytes(s.get(),2));if(parsed.feed_id()!=f.feed_id||parsed.sequence()!=static_cast<std::uint64_t>(n)||parsed.id()!=id)throw std::runtime_error("corrupt history head");return {static_cast<std::uint64_t>(n),std::move(id)};}
ContextHistoryRange SQLiteContextStore::snapshot_history(const ContextStoreFeed& f,std::uint64_t from,std::uint64_t through)const{validate_feed(f);if(!from||through<from||through-from>=InMemoryContextStore::MAX_RANGE_RECORDS)throw std::invalid_argument("invalid range");std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT sequence,record_id,canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 AND sequence>=?3 AND sequence<=?4 ORDER BY sequence");s.text(1,f.owner_id);s.text(2,f.feed_id);s.i64(3,from);s.i64(4,through);std::string jsonl;for(auto n=from;s.row();++n){if(sqlite3_column_int64(s.get(),0)!=static_cast<sqlite3_int64>(n))throw std::out_of_range("range is not present");auto id=text(s.get(),1);auto b=bytes(s.get(),2);auto parsed=RuntimeHistoryRecord::parse(b);if(parsed.feed_id()!=f.feed_id||parsed.sequence()!=n||parsed.id()!=id)throw std::runtime_error("corrupt history snapshot");if(b.size()+(jsonl.empty()?0:1)>InMemoryContextStore::MAX_RANGE_BYTES-jsonl.size())throw std::invalid_argument("range too large");if(!jsonl.empty())jsonl+='\n';jsonl+=b;}if(jsonl.empty()||std::count(jsonl.begin(),jsonl.end(),'\n')+1!=through-from+1)throw std::out_of_range("range is not present");ContextHistoryRange r{f.owner_id,f.feed_id,from,through,digest(jsonl),{}};r.artifact_uri=uri(r);return r;}
std::string SQLiteContextStore::hydrate_history(const ContextHistoryRange& r)const{validate_feed({r.owner_id,r.feed_id});if(!r.from_sequence||r.through_sequence<r.from_sequence||r.through_sequence-r.from_sequence>=InMemoryContextStore::MAX_RANGE_RECORDS||!detail::is_sha256_identity(r.digest)||r.artifact_uri!=uri(r))throw std::invalid_argument("invalid range");std::lock_guard l(impl_->mu);std::optional<std::string> prev;if(r.from_sequence>1){Stmt p(impl_->db,"SELECT canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 AND sequence=?3");p.text(1,r.owner_id);p.text(2,r.feed_id);p.i64(3,r.from_sequence-1);if(!p.row())throw std::invalid_argument("broken history chain");prev=RuntimeHistoryRecord::parse(bytes(p.get(),0)).id();}Stmt s(impl_->db,"SELECT sequence,canonical FROM ng_runtime_history WHERE owner_id=?1 AND feed_id=?2 AND sequence>=?3 AND sequence<=?4 ORDER BY sequence");s.text(1,r.owner_id);s.text(2,r.feed_id);s.i64(3,r.from_sequence);s.i64(4,r.through_sequence);std::string out;for(auto n=r.from_sequence;n<=r.through_sequence;++n){if(!s.row()||sqlite3_column_int64(s.get(),0)!=static_cast<sqlite3_int64>(n))throw std::invalid_argument("broken history chain");auto b=bytes(s.get(),1);auto x=RuntimeHistoryRecord::parse(b);if(x.feed_id()!=r.feed_id||x.sequence()!=n||(n==1?x.predecessor_id().has_value():!x.predecessor_id()||!prev||*x.predecessor_id()!=*prev))throw std::invalid_argument("broken history chain");prev=x.id();if(!out.empty())out+='\n';out+=b;}if(digest(out)!=r.digest)throw std::invalid_argument("range digest mismatch");return out;}
ContextArtifactPutResult SQLiteContextStore::put_artifact(std::string_view owner,const ContextArtifact& a){validate_owner(owner);auto b=a.serialize_canonical();if(b.size()>InMemoryContextStore::MAX_ARTIFACT_BYTES)throw std::invalid_argument("artifact too large");std::lock_guard l(impl_->mu);Tx tx(impl_->db);Stmt s(impl_->db,"SELECT canonical FROM ng_runtime_artifacts WHERE owner_id=?1 AND artifact_id=?2");s.text(1,owner);s.text(2,a.id());if(s.row()){auto result=bytes(s.get(),0)==b?ContextArtifactPutResult::AlreadyPresent:ContextArtifactPutResult::Conflict;tx.commit();return result;}Stmt p(impl_->db,"INSERT INTO ng_runtime_artifacts VALUES(?1,?2,?3)");p.text(1,owner);p.text(2,a.id());p.text(3,b);p.done();tx.commit();return ContextArtifactPutResult::Stored;}
std::optional<ContextArtifact> SQLiteContextStore::get_artifact(std::string_view owner,std::string_view id)const{validate_owner(owner);if(!detail::is_sha256_identity(id))throw std::invalid_argument("invalid artifact id");std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT canonical FROM ng_runtime_artifacts WHERE owner_id=?1 AND artifact_id=?2");s.text(1,owner);s.text(2,id);if(!s.row())return{};return ContextArtifact::parse(bytes(s.get(),0));}

struct SQLiteHookJournal::Impl { explicit Impl(std::string p){open(db,p);} ~Impl(){if(db)sqlite3_close_v2(db);} sqlite3* db=nullptr;mutable std::mutex mu;};
SQLiteHookJournal::SQLiteHookJournal(std::string p):impl_(std::make_unique<Impl>(std::move(p))){} SQLiteHookJournal::~SQLiteHookJournal()=default; SQLiteHookJournal::SQLiteHookJournal(SQLiteHookJournal&&) noexcept=default; SQLiteHookJournal& SQLiteHookJournal::operator=(SQLiteHookJournal&&) noexcept=default;
HookOutboxEntry SQLiteHookJournal::enqueue(HookInvocation i,RuntimeEvent e,std::uint32_t max,Clock::time_point deadline){auto candidate=HookOutboxEntry::create({std::move(i),std::move(e),HookExecutionState::Triggered,0,max,deadline});std::lock_guard l(impl_->mu);Tx tx(impl_->db);auto existing=hook(impl_->db,candidate.data().invocation.id());if(existing){if(existing->data().invocation.serialize_canonical()!=candidate.data().invocation.serialize_canonical()||existing->data().event.serialize_canonical()!=candidate.data().event.serialize_canonical()||existing->data().max_attempts!=max||existing->data().deadline!=deadline)throw std::invalid_argument("logical hook invocation enqueue conflict");tx.commit();return *existing;}Stmt s(impl_->db,"INSERT INTO ng_hook_outbox VALUES(?1,?2,?3)");s.text(1,candidate.data().invocation.id());s.text(2,candidate.serialize_canonical());s.i64(3,static_cast<unsigned>(candidate.data().state));s.done();tx.commit();return candidate;}
HookOutboxEntry SQLiteHookJournal::publish(std::string_view id){std::lock_guard l(impl_->mu);Tx tx(impl_->db);auto e=hook(impl_->db,id);if(!e)throw std::out_of_range("hook invocation is not enqueued");if(e->data().state==HookExecutionState::Triggered){auto d=e->data();d.state=HookExecutionState::Pending;*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);}tx.commit();return *e;}
std::optional<HookLease> SQLiteHookJournal::claim(std::string_view id,std::string_view worker,Clock::time_point now,std::chrono::milliseconds duration){if(worker.empty()||duration<=std::chrono::milliseconds::zero())throw std::invalid_argument("invalid hook claim");std::lock_guard l(impl_->mu);Tx tx(impl_->db);auto e=hook(impl_->db,id);if(!e){tx.commit();return{};}auto d=e->data();if(d.deadline<=now&&!terminal(d.state)){d.state=HookExecutionState::TimedOut;d.lease_expires_at={};*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return{};}if(d.state==HookExecutionState::Dispatched&&d.lease_expires_at<=now){d.lease_expires_at={};if(d.invocation.data().idempotency==HookIdempotency::NonIdempotent){d.state=HookExecutionState::ReconciliationRequired;d.receipt=HookExecutionReceipt::create({d.invocation.id(),d.attempt_count,HookExecutionState::ReconciliationRequired,{},"non-idempotent dispatched lease expired; external outcome is unknown"});*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return{};}d.state=HookExecutionState::Failed;d.receipt=HookExecutionReceipt::create({d.invocation.id(),d.attempt_count,HookExecutionState::Failed,{},"idempotent dispatched lease expired"});*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);d=e->data();}if(d.state!=HookExecutionState::Pending&&!(d.state==HookExecutionState::Failed&&d.attempt_count<d.max_attempts)){tx.commit();return{};}if(d.attempt_count>=d.max_attempts){d.state=HookExecutionState::TimedOut;*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return{};}d.state=HookExecutionState::Dispatched;++d.attempt_count;++d.fencing_token;d.receipt.reset();d.lease_expires_at=std::min(d.deadline,now+duration);*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return HookLease{*e,e->data().fencing_token};}
std::optional<HookOutboxEntry> SQLiteHookJournal::settle(std::string_view id,std::uint64_t fence,HookExecutionReceipt receipt,Clock::time_point now){std::lock_guard l(impl_->mu);Tx tx(impl_->db);auto e=hook(impl_->db,id);if(!e){tx.commit();return{};}auto d=e->data();if(d.state!=HookExecutionState::Dispatched||d.fencing_token!=fence||d.lease_expires_at<now||receipt.data().invocation_id!=id||receipt.data().attempt!=d.attempt_count){tx.commit();return{};}d.receipt=std::move(receipt);d.state=d.receipt->data().state;d.lease_expires_at={};if(d.state==HookExecutionState::Failed&&d.attempt_count>=d.max_attempts)d.state=HookExecutionState::TimedOut;*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return e;}
std::optional<HookOutboxEntry> SQLiteHookJournal::reconcile(std::string_view id,HookExecutionState expected,std::string_view head,std::uint64_t fence,HookExecutionReceipt known){std::lock_guard l(impl_->mu);Tx tx(impl_->db);auto e=hook(impl_->db,id);if(!e||e->data().state!=expected||e->id()!=head||e->data().fencing_token!=fence||expected!=HookExecutionState::ReconciliationRequired||!known.data().external_effect.outcome_known||known.data().invocation_id!=id||known.data().attempt!=e->data().attempt_count||(known.data().state!=HookExecutionState::Succeeded&&known.data().state!=HookExecutionState::Failed)){tx.commit();return{};}auto d=e->data();d.state=known.data().state;d.receipt=std::move(known);*e=HookOutboxEntry::create(std::move(d));save_hook(impl_->db,*e);tx.commit();return e;}
std::optional<HookOutboxEntry> SQLiteHookJournal::get(std::string_view id)const{std::lock_guard l(impl_->mu);return hook(impl_->db,id);}
std::vector<HookOutboxEntry> SQLiteHookJournal::pending()const{std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT invocation_id,canonical,state FROM ng_hook_outbox");std::vector<HookOutboxEntry> out;while(s.row()){auto id=text(s.get(),0);auto canonical=bytes(s.get(),1);auto entry=checked_hook(id,sqlite3_column_int64(s.get(),2),canonical);auto state=entry.data().state;if(state==HookExecutionState::Triggered||state==HookExecutionState::Pending||state==HookExecutionState::Dispatched||state==HookExecutionState::Failed)out.push_back(std::move(entry));}return out;}
std::vector<HookOutboxEntry> SQLiteHookJournal::reconciliation_required()const{std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT invocation_id,canonical,state FROM ng_hook_outbox");std::vector<HookOutboxEntry> out;while(s.row()){auto id=text(s.get(),0);auto canonical=bytes(s.get(),1);auto entry=checked_hook(id,sqlite3_column_int64(s.get(),2),canonical);if(entry.data().state==HookExecutionState::ReconciliationRequired)out.push_back(std::move(entry));}return out;}

struct SQLiteProviderDispatchReceiptStore::Impl { explicit Impl(std::string p){open(db,p);} ~Impl(){if(db)sqlite3_close_v2(db);} sqlite3* db=nullptr;mutable std::mutex mu;};
SQLiteProviderDispatchReceiptStore::SQLiteProviderDispatchReceiptStore(std::string p):impl_(std::make_unique<Impl>(std::move(p))){} SQLiteProviderDispatchReceiptStore::~SQLiteProviderDispatchReceiptStore()=default; SQLiteProviderDispatchReceiptStore::SQLiteProviderDispatchReceiptStore(SQLiteProviderDispatchReceiptStore&&) noexcept=default; SQLiteProviderDispatchReceiptStore& SQLiteProviderDispatchReceiptStore::operator=(SQLiteProviderDispatchReceiptStore&&) noexcept=default;
ProviderDispatchReceiptPutResult SQLiteProviderDispatchReceiptStore::persist(const ProviderDispatchReceipt& r){return persist({},r);}
ProviderDispatchReceiptPutResult SQLiteProviderDispatchReceiptStore::persist(std::string_view owner,const ProviderDispatchReceipt& r){validate_receipt_owner(owner);auto b=r.serialize_canonical();std::lock_guard l(impl_->mu);Tx tx(impl_->db);Stmt s(impl_->db,"SELECT canonical FROM ng_provider_receipts WHERE owner_scope=?1 AND dispatch_id=?2");s.text(1,owner);s.text(2,r.dispatch_id());if(s.row()){const auto stored=bytes(s.get(),0);if(ProviderDispatchReceipt::parse(stored).dispatch_id()!=r.dispatch_id())throw std::runtime_error("SQLite provider receipt dispatch identity mismatch");auto result=stored==b?ProviderDispatchReceiptPutResult::AlreadyPresent:ProviderDispatchReceiptPutResult::Conflict;tx.commit();return result;}Stmt p(impl_->db,"INSERT INTO ng_provider_receipts VALUES(?1,?2,?3)");p.text(1,owner);p.text(2,r.dispatch_id());p.text(3,b);p.done();tx.commit();return ProviderDispatchReceiptPutResult::Stored;}
ProviderDispatchState SQLiteProviderDispatchReceiptStore::state(std::string_view id)const{return state({},id);}
ProviderDispatchState SQLiteProviderDispatchReceiptStore::state(std::string_view owner,std::string_view id)const{validate_receipt_owner(owner);std::lock_guard l(impl_->mu);Stmt s(impl_->db,"SELECT canonical FROM ng_provider_receipts WHERE owner_scope=?1 AND dispatch_id=?2");s.text(1,owner);s.text(2,id);if(!s.row())return ProviderDispatchState::Missing;auto receipt=ProviderDispatchReceipt::parse(bytes(s.get(),0));if(receipt.dispatch_id()!=id)throw std::runtime_error("SQLite provider receipt dispatch identity mismatch");return ProviderDispatchState::AdmittedPending;}
}  // namespace neograph
