#!/usr/bin/env python3
"""Generate a C++ header with embedded JSON schema strings.

Usage:
    python3 embed_schemas.py <schemas_dir> <output_header>

Example:
    python3 embed_schemas.py schemas/ build/generated/builtin_schemas.h
"""

import os
import sys
import json


def escape_for_raw_string(content: str) -> str:
    """Check if content is safe for R\"(...)\" raw string literal."""
    if ')\"' in content:
        # Use a delimiter to avoid ambiguity
        return None
    return content


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <schemas_dir> <output_header>")
        sys.exit(1)

    schemas_dir = sys.argv[1]
    output_path = sys.argv[2]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    schemas = {}
    for filename in sorted(os.listdir(schemas_dir)):
        if not filename.endswith('.json'):
            continue
        name = filename[:-5]  # strip .json
        filepath = os.path.join(schemas_dir, filename)
        with open(filepath, 'r') as f:
            content = f.read().strip()
            # Validate JSON
            json.loads(content)
            schemas[name] = content

    with open(output_path, 'w') as out:
        out.write("// Auto-generated by scripts/embed_schemas.py — DO NOT EDIT\n")
        out.write("#pragma once\n\n")
        out.write("#include <string>\n")
        out.write("#include <map>\n\n")
        out.write("namespace neograph::llm::builtin {\n\n")

        for name, content in schemas.items():
            var_name = f"schema_{name}"
            out.write(f'inline const char* {var_name} = R"(\n')
            out.write(content)
            out.write('\n)";\n\n')

        # Registry map
        out.write("inline const std::map<std::string, const char*>& schemas() {\n")
        out.write("    static const std::map<std::string, const char*> m = {\n")
        for name in schemas:
            out.write(f'        {{"{name}", schema_{name}}},\n')
        out.write("    };\n")
        out.write("    return m;\n")
        out.write("}\n\n")

        out.write("} // namespace neograph::llm::builtin\n")

    print(f"Generated {output_path} with {len(schemas)} schemas: {', '.join(schemas.keys())}")


if __name__ == "__main__":
    main()
