#!/usr/bin/env python3
"""Generate a C++ header with embedded JSON schema strings.

Usage:
    python3 embed_schemas.py <schemas_dir> <output_header>

Example:
    python3 embed_schemas.py schemas/ build/generated/builtin_schemas.h
"""

import json
import os
import re
import sys


def cpp_identifier(name: str) -> str:
    """Return a deterministic C++ identifier for an arbitrary schema filename."""
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if identifier and identifier[0].isdigit():
        identifier = "_" + identifier
    return "schema_" + identifier


def raw_string_delimiter(content: str) -> str:
    """Return a C++ raw-string delimiter absent from the schema content."""
    for candidate in (f"NG{index:X}" for index in range(1_000_000)):
        if f'){candidate}"' not in content:
            return candidate
    raise ValueError("Unable to choose a collision-free C++ raw-string delimiter")


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <schemas_dir> <output_header>")
        sys.exit(1)

    schemas_dir = sys.argv[1]
    output_path = sys.argv[2]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    schemas = {}
    for filename in sorted(os.listdir(schemas_dir)):
        if not filename.endswith('.json'):
            continue
        name = filename[:-5]  # strip .json
        filepath = os.path.join(schemas_dir, filename)
        with open(filepath, 'r') as f:
            content = f.read().strip()
            # Validate JSON
            json.loads(content)
            schemas[name] = content

    with open(output_path, 'w', encoding='utf-8') as out:
        out.write("// Auto-generated by scripts/embed_schemas.py -- DO NOT EDIT\n")
        out.write("#pragma once\n\n")
        out.write("#include <string>\n")
        out.write("#include <map>\n\n")
        out.write("namespace neograph::llm::builtin {\n\n")

        identifiers = {name: cpp_identifier(name) for name in schemas}
        if len(set(identifiers.values())) != len(identifiers):
            raise ValueError("Schema filenames collide after C++ identifier normalization")
        for name, content in schemas.items():
            var_name = identifiers[name]
            delimiter = raw_string_delimiter(content)
            out.write(f'inline const char* {var_name} = R"{delimiter}(\n')
            out.write(content)
            out.write(f'\n){delimiter}";\n\n')

        # Registry map
        out.write("inline const std::map<std::string, const char*>& schemas() {\n")
        out.write("    static const std::map<std::string, const char*> m = {\n")
        for name, var_name in identifiers.items():
            out.write(f'        {{"{name}", {var_name}}},\n')
        out.write("    };\n")
        out.write("    return m;\n")
        out.write("}\n\n")

        out.write("} // namespace neograph::llm::builtin\n")

    print(f"Generated {output_path} with {len(schemas)} schemas: {', '.join(schemas.keys())}")


if __name__ == "__main__":
    main()
